---
- name: lui a host
  hosts: router-dev
  gather_facts: True
  tasks:

  - name: apt installs
    apt:
      state: present
      pkg: 
      - dos2unix
      - python3
      - p7zip-full
      - cpio
      - gzip
      - genisoimage
      - whois
      - pwgen
      - wget
      - fakeroot
      - isolinux
      - xorriso
      - tree
    become: true

  - name: build lui directories
    file:
      path: /home/ubuntu/lui/ubuntu/20.04-router/custom
      state: directory 
      mode: '0755'
      owner: "{{ user }}"
      group: "{{ user }}"
    become: true

  - debug: 
      msg: "Here's the NIC MAC: {{ hostvars[item].nic_mac }}" 
    tags: buggy
    loop: "{{ groups['dev'] }}"

  - name: Set authorized keys taken from url
    authorized_key:
      path: /home/ubuntu/lui/ubuntu/20.04-router/custom/authorized_keys"
      user: "{{ user }}" 
      state: present
      key: "https://github.com/{{ item }}.keys"
    loop:
      - sfeeser
      - seaneon
      - bryfry
      - sgriffith3

  - name: Configure Templates
    template:
      src: "ubuntu/20.04-router/custom/{{ item.src }}"
      dest: "{{ user_path }}//lui/ubuntu/20.04-router/custom/{{ item.dest }}"
      mode: '0644'
      owner: "{{ user }}"
      group: "{{ user }}"
    become: true
    loop:
     - src:  rules.v4.j2
       dest: rules.v4
     - src:  dnsmasq.conf.j2   
       dest: dnsmasq.conf
     - src:  dnsmasq.dhcp-hosts.UNDERCLOUD.j2   
       dest: dnsmasq.dhcp-hosts.UNDERCLOUD
     - src:  dnsmasq.dhcp-options.UNDERCLOUD.j2  
       dest: dnsmasq.dhcp-options.UNDERCLOUD
     - src:  dnsmasq.hosts.UNDERCLOUD.j2  
       dest: dnsmasq.hosts.UNDERCLOUD
     - src:  sshd_conf.j2
       dest: sshd_conf
     - src:  netplan.j2
       dest: netplan
     - src:  preseed.cfg.j2
       dest: preseed.cfg 

  - name: Copy build-iso.sh to destination
    copy:
      src: "templates/ubuntu/20.04-router/{{ item.src }}" 
      dest: "/home/{{ user }}/lui/ubuntu/20.04-router/{{ item.dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    loop:
    - src:  build-iso.sh
      dest: build-iso.sh
    - src:  custom/boot-menu.patch
      dest: custom/boot-menu.patch



#  - name: run build-iso-sh

#  - name: hdparm the key

#  - name: dd the key

#  - name: dd the mbr of sda

#  - name: reboot

