---
- name: BOOTSTRAPPING HOSTS
  hosts: router-dev
  gather_facts: True
  tasks:

  - name: apt installs
    apt:
      state: present
      pkg: 
      - dos2unix
      - python3
      - p7zip-full
      - cpio
      - gzip
      - genisoimage
      - whois
      - pwgen
      - wget
      - fakeroot
      - isolinux
      - xorriso
      - tree
      - patch
    become: true

  - name: Clean lui directories  (delete them)
    file:
      path: /home/{{ user }}/lui
      state: absent
    become: true

  - name: build lui directories
    file:
      path: /home/{{ user }}/lui/{{ lui_path }}/custom
      state: directory 
      mode: '0755'
      owner: "{{ user }}"
      group: "{{ user }}"
    become: true

  - debug: 
      msg: '{{poweroff_when_done}}' 
    tags: buggy

  - name: Set authorized keys from url
    authorized_key:
      path: "/home/{{ user }}/lui/{{ lui_path }}/custom/authorized_keys"
      user: "{{ user }}" 
      state: present
      key: "https://github.com/{{ item }}.keys"
    loop: "{{ keys }}"

  - name: Add this computer's RSA key for bootstrapping only
    authorized_key:
      path: "/home/{{ user }}/lui/{{ lui_path }}/custom/authorized_keys"
      user: "{{ user }}" 
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Universal Host Templates
    template:
      src: "{{ lui_path }}/custom/{{ item.src }}"
      dest: "/home/{{ user }}//lui/{{ lui_path }}/custom/{{ item.dest }}"
      mode: '0644'
      owner: "{{ user }}"
      group: "{{ user }}"
    become: true
    loop:
     - src:  sshd_conf.j2
       dest: sshd_conf
     - src:  netplan.j2
       dest: netplan
     - src:  preseed.cfg.j2
       dest: preseed.cfg 
     - src:  ssh-host-keygen.service
       dest: ssh-host-keygen.service

  - name: Router specific templates
    template:
      src: "{{ lui_path }}/custom/{{ item.src }}"
      dest: "/home/{{ user }}//lui/{{ lui_path }}/custom/{{ item.dest }}"
      mode: '0644'
      owner: "{{ user }}"
      group: "{{ user }}"
    become: true
    when: router
    loop:
     - src:  rules.v4.j2
       dest: rules.v4
     - src:  dnsmasq.conf.j2   
       dest: dnsmasq.conf
     - src:  dnsmasq.dhcp-hosts.UNDERCLOUD.j2   
       dest: dnsmasq.dhcp-hosts.UNDERCLOUD
     - src:  dnsmasq.dhcp-options.UNDERCLOUD.j2  
       dest: dnsmasq.dhcp-options.UNDERCLOUD
     - src:  dnsmasq.hosts.UNDERCLOUD.j2  
       dest: dnsmasq.hosts.UNDERCLOUD

  - name: Copy build-iso.sh to destination
    copy:
      src: "templates/{{ lui_path }}/{{ item.src }}" 
      dest: "/home/{{ user }}/lui/{{ lui_path }}/{{ item.dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    loop:
    - src:  build-iso.sh
      dest: build-iso.sh
    - src:  custom/boot-menu.patch
      dest: custom/boot-menu.patch

  - name: run build-iso-sh
    shell: "./{{ lui_path }}/build-iso.sh  /home/{{ user }}/lui.iso"
    args:
      chdir: /home/{{ user }}/lui

  - name: hdparm the key
    shell: hdparm -r0 /dev/sdb1
    become: true

  - name: umount the USB
    mount:
      path: /usb
      state: unmounted
    become: true
    when: unarchive_iso_for_testing

  - name: WRITE THE ISO to USB
    shell: cat lui.iso > /dev/sdb
    become: true

  - name: Clean test directory
    file:
      path: /home/{{ user }}/iso-cracker
      state: absent
    become: true
    when: unarchive_iso_for_testing

  - name: Make a test directory
    file:
      path: /home/{{ user }}/iso-cracker
      state: directory 
      mode: '0755'
      owner: "{{ user }}"
      group: "{{ user }}"
    when: unarchive_iso_for_testing  

  - name: dd the key
    shell: dd bs=4M if=/home/{{ user }}/lui.iso of=/dev/sdb1 conv=fdatasync
    become: true
    when: unarchive_iso_for_testing
     
  - name: mount the USB
    shell: mount /dev/sdb1 /usb
    become: true  
    when: unarchive_iso_for_testing

  - shell: cp /usb/initrd.gz /home/{{ user }}/iso-cracker 
    when: unarchive_iso_for_testing

  - shell: gunzip ~/iso-cracker/initrd.gz
    when: unarchive_iso_for_testing

  - shell: cpio -i < initrd 
    args:
      chdir: /home/{{ user }}/iso-cracker
    ignore_errors: yes
    when: unarchive_iso_for_testing

  - name: umount the USB
    mount:
      path: /usb
      state: unmounted
    become: true
    when: unarchive_iso_for_testing

#  - name: dd the mbr of sda

#  - name: reboot

#  - run finishing tasks  
